name: CI_action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build :
<<<<<<< HEAD
    runs-on: ubuntu-latest
    defaults:
       run:  
     working-directory: ./frontend
=======

    runs-on: ubuntu-latest
    defaults:
        run:   
        working-directory: ./frontend
>>>>>>> 3ce728c92a13d89b33da3249831bbb2527abf6b5

    strategy:
      matrix:
        node-version: [14.x]
<<<<<<< HEAD
=======

>>>>>>> 3ce728c92a13d89b33da3249831bbb2527abf6b5
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests
      run: npm test

    - name: Build
      run: npm run build
